// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mongodb

import (
	"github.com/blackhorseya/ekko/entity/domain/workflow/repo"
	"github.com/blackhorseya/ekko/pkg/storage/mongodbx"
	"github.com/google/wire"
)

// Injectors from wire.go:

func BuildIssueRepo() (repo.IIssueRepo, error) {
	client, err := mongodbx.NewClient()
	if err != nil {
		return nil, err
	}
	iIssueRepo := NewIssueRepo(client)
	return iIssueRepo, nil
}

// wire.go:

// IssueMongodbSet is the set of IssueMongodbSet.
var IssueMongodbSet = wire.NewSet(
	NewIssueRepo, mongodbx.NewClient,
)
