// Code generated by mockery v2.14.0. DO NOT EDIT.

package repo

import (
	contextx "github.com/blackhorseya/gocommon/pkg/contextx"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockIRepo is an autogenerated mock type for the IRepo type
type MockIRepo struct {
	mock.Mock
}

// Ping provides a mock function with given fields: ctx, timeout
func (_m *MockIRepo) Ping(ctx contextx.Contextx, timeout time.Duration) error {
	ret := _m.Called(ctx, timeout)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx, time.Duration) error); ok {
		r0 = rf(ctx, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockIRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIRepo creates a new instance of MockIRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIRepo(t mockConstructorTestingTNewMockIRepo) *MockIRepo {
	mock := &MockIRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
