basePath: /api
definitions:
  er.APPError:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  pb.Task:
    properties:
      created_at:
        type: string
      id:
        type: integer
      status:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Cheng
    url: https://blog.seancheng.space
  description: TodoList API
  license:
    name: GPL-3.0
    url: https://spdx.org/licenses/GPL-3.0-only.html
  title: TodoList API
  version: 0.0.1
paths:
  /liveness:
    get:
      consumes:
      - application/json
      description: to know when to restart an application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APPError'
      summary: Liveness
      tags:
      - Health
  /readiness:
    get:
      consumes:
      - application/json
      description: Show application was ready to start accepting traffic
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APPError'
      summary: Readiness
      tags:
      - Health
  /v1/tasks:
    get:
      consumes:
      - application/json
      description: List all tasks
      parameters:
      - default: 0
        description: start
        in: query
        name: start
        type: integer
      - default: 10
        description: end
        in: query
        name: end
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/pb.Task'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/er.APPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APPError'
      summary: List all tasks
      tags:
      - Tasks
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Create a task
      parameters:
      - description: title
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/pb.Task'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APPError'
      summary: Create a task
      tags:
      - Tasks
  /v1/tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a task by id
      parameters:
      - description: ID of task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/er.APPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APPError'
      summary: Delete a task by id
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      description: Get a task by id
      parameters:
      - description: ID of task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/pb.Task'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/er.APPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APPError'
      summary: Get a task by id
      tags:
      - Tasks
  /v1/tasks/{id}/status:
    patch:
      consumes:
      - application/x-www-form-urlencoded
      description: Update task's status by id
      parameters:
      - description: ID of task
        in: path
        name: id
        required: true
        type: string
      - description: status
        in: formData
        name: status
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/pb.Task'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APPError'
      summary: Update task's status by id
      tags:
      - Tasks
  /v1/tasks/{id}/title:
    patch:
      consumes:
      - application/x-www-form-urlencoded
      description: Change task's title by id
      parameters:
      - description: ID of task
        in: path
        name: id
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/pb.Task'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APPError'
      summary: Change task's title by id
      tags:
      - Tasks
swagger: "2.0"
