// Code generated by MockGen. DO NOT EDIT.
// Source: notifier.go

// Package notifier is a generated GoMock package.
package notifier

import (
	reflect "reflect"

	contextx "github.com/blackhorseya/ekko/pkg/contextx"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// SendText mocks base method.
func (m *MockNotifier) SendText(ctx contextx.Contextx, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendText", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendText indicates an expected call of SendText.
func (mr *MockNotifierMockRecorder) SendText(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendText", reflect.TypeOf((*MockNotifier)(nil).SendText), ctx, message)
}
