language: go

git:
  submodules: false

cache:
  directories:
    - "$HOME/.cache/go-build"
    - "$HOME/gopath/pkg/mod"

go:
  - '1.15'

services:
  - docker

env:
  global:
    - GO111MODULE=on

stages:
  - Tests
  - Static Code Analytic
  - name: Deploy
    if: branch =~ /^release-\d+\.\d+$/

jobs:
  include:
    - stage: Tests
      name: Unit Test
      script:
        - echo $docker_password | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io
        - make test-with-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: Integration Test
      script:
        - echo "execute integration test..."
    - stage: Static Code Analytic
      name: Lint
      script:
        - make lint
    - stage: Deploy
      script:
        - echo $docker_password | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io
        - make build-image
        - make tag-image
        - make push-image
