language: go

go:
  - "1.15"

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  - GO111MODULE=on
  - CODECOV_TOKEN=aa0a457a-579e-43f3-8126-f0137aa9e040

before_install:
  - make install-tools
  - make install-mod

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - test
  - static code analytic
  - name: deploy
    if: branch = release

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script:
        - make test-with-coverage
    - stage: static code analytic
      name: "Lint"
      script:
        - make lint
