language: go

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/'"$GITHUB_USER"':'"$GITHUB_TOKEN"'@github.com\//' .gitmodules
  - git submodule update --init --recursive

cache:
  directories:
    - "$HOME/.cache/go-build"
    - "$HOME/gopath/pkg/mod"

go:
  - '1.15'

env:
  global:
    - GO111MODULE=on

stages:
  - Tests
  - name: Deploy
    if: tag =~ ^v

jobs:
  include:
    - stage: Tests
      name: Unit Test
      script:
        - make test-unit
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: Integration Test
      script:
        - echo "execute integration test..."
    - name: Report
      script:
        - make report
    - stage: Deploy
      services:
        - docker
      install:
        - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - echo $KUBECONFIG | base64 --decode > ${HOME}/kubeconfig.yaml && export KUBECONFIG=${HOME}/kubeconfig.yaml
        - echo $DOCKER_PASSWORD | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io
        - export version=$(echo $TRAVIS_TAG | cut -c 2-)
      script:
        - make build-image VERSION=$version
        - make tag-image VERSION=$version
        - make push-image VERSION=$version
        - make deploy NS=side DEPLOY_TO=prod VERSION=$version
