language: go

go:
  - "1.15"

env:
  - GO111MODULE=on
  - CODECOV_TOKEN=aa0a457a-579e-43f3-8126-f0137aa9e040

before_install:
  - make install-tools

install:
  - make install-mod

script:
  - make lint
  - make test-with-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
