language: go

cache:
  directories:
    - "$HOME/.cache/go-build"
    - "$HOME/gopath/pkg/mod"

go:
  - '1.15'

services:
  - docker

env:
  global:
    - GO111MODULE=on

before_install:
  - openssl aes-256-cbc -K $encrypted_7961871dbabc_key -iv $encrypted_7961871dbabc_iv -in sean-side-uat-gcr-pusher.json.enc -out sean-side-uat-gcr-pusher.json -d

stages:
  - Tests
  - Static Code Analytic
  - name: Deploy
    if: branch =~ /^release-\d+\.\d+$/

jobs:
  include:
    - stage: Tests
      name: Unit Test
      script:
        - make test-with-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: Integration Test
      script:
        - echo "execute integration test..."
    - stage: Static Code Analytic
      name: Lint
      script:
        - make lint
    - stage: Deploy
      script:
        - cat sean-side-uat-gcr-pusher.json | docker login -u _json_key --password-stdin https://gcr.io
        - make build-image
        - make tag-image
        - make push-image
