language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

go:
  - "1.15"

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - CODECOV_TOKEN=aa0a457a-579e-43f3-8126-f0137aa9e040

stages:
  - Tests
  - Static Code Analytic
  - name: Deploy
    if: branch =~ /^release-\d+\.\d+$/

jobs:
  include:
    - stage: "Tests"
      name: "Unit Test"
      script:
        - make test-with-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: "Integration Test"
      script:
        - echo "execute integration test..."
    - stage: "Static Code Analytic"
      name: "Lint"
      script:
        - make lint
    - stage: "Deploy"
      name: "Build Docker Image"
      script:
        - make build-image
