service: ekko

frameworkVersion: '3'

plugins:
  - serverless-go-plugin

custom:
  go:
    baseDir: . # folder where go.mod file lives, if set `handler` property should be set relatively to that folder
    binDir: bin # target folder for binary files
    cgo: 0 # CGO_ENABLED flag
    cmd: 'GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"' # compile command
    monorepo: false # if enabled, builds function every directory (useful for monorepo where go.mod is managed by each function
    supportedRuntimes: [ "provided.al2023" ] # the plugin compiles a function only if runtime is declared here (either on function or provider level)
    buildProvidedRuntimeAsBootstrap: true # if enabled, builds and archive function with only single "bootstrap" binary (useful for runtimes like provided.al2)

provider:
  name: aws
  runtime: provided.al2023
  stage: ${opt:stage, 'prod'}
  region: ap-northeast-1

package:
  individually: true

functions:
  # api
  platformRest:
    handler: ./adapter/platform/rest/lambda/
    name: ${sls:stage}-${self:service}-platform-rest
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
    environment: ${file(./deployments/${opt:stage, 'prod'}/.env.yaml)}
