// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/blackhorseya/ekko/pkg/httpx"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func CreateMariadb(rw *sqlx.DB) IRepo {
	iRepo := NewMariadb(rw)
	return iRepo
}

func CreateHTTPClient(v *viper.Viper, client httpx.Client) (IRepo, error) {
	iRepo, err := NewHTTPClient(v, client)
	if err != nil {
		return nil, err
	}
	return iRepo, nil
}

// wire.go:

var testProviderMariadbSet = wire.NewSet(NewMariadb)

var testProviderHTTPClientSet = wire.NewSet(NewHTTPClient)
