// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	"github.com/blackhorseya/ekko/app/domain/workflow/repo/issue/mongodb"
	"github.com/blackhorseya/ekko/entity/domain/workflow/biz"
	"github.com/blackhorseya/ekko/pkg/storage/mongodbx"
	"github.com/google/wire"
)

// Injectors from wire.go:

func BuildWorkflowBiz() (biz.IWorkflowBiz, error) {
	client, err := mongodbx.NewClient()
	if err != nil {
		return nil, err
	}
	iIssueRepo := mongodb.NewIssueRepo(client)
	iWorkflowBiz := NewWorkflowBiz(iIssueRepo)
	return iWorkflowBiz, nil
}

// wire.go:

// DefaultWorkflowSet is the set of DefaultWorkflowSet.
var DefaultWorkflowSet = wire.NewSet(
	NewWorkflowBiz, mongodb.IssueMongodbSet,
)
