// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package task

import (
	"github.com/blackhorseya/todo-app/internal/app/biz/task"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateTaskHandler(taskBiz task.Biz) (IHandler, error) {
	iHandler := NewImpl(taskBiz)
	return iHandler, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
