// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/ekko/internal/adapter/issue/restful"
	"github.com/blackhorseya/ekko/internal/app/domain/issue/biz"
	"github.com/blackhorseya/ekko/internal/app/domain/issue/biz/repo"
	"github.com/blackhorseya/ekko/internal/pkg/config"
	"github.com/blackhorseya/ekko/internal/pkg/genx"
	"github.com/blackhorseya/ekko/internal/pkg/httpx"
	"github.com/blackhorseya/ekko/internal/pkg/log"
	"github.com/blackhorseya/ekko/internal/pkg/storage/mariadb"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateService(path2 string, id int64) (*Service, error) {
	configConfig, err := config.NewWithPath(path2)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	engine := httpx.NewRouter()
	server := httpx.NewServer(configConfig, logger, engine)
	db, err := mariadb.NewMariadb(configConfig, logger)
	if err != nil {
		return nil, err
	}
	iRepo := repo.NewMariadb(db)
	generator, err := genx.NewImpl(id)
	if err != nil {
		return nil, err
	}
	iBiz := biz.NewImpl(iRepo, generator)
	adaptersRestful := restful.NewRestful(logger, engine, iBiz)
	service, err := NewService(logger, server, adaptersRestful)
	if err != nil {
		return nil, err
	}
	return service, nil
}

// wire.go:

var providerSet = wire.NewSet(config.NewWithPath, log.NewLogger, genx.ProviderSet, mariadb.ProviderSet, httpx.ServerSet, restful.IssueSet, biz.IssueSet, repo.ProvideMariadb, NewService)
