// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/blackhorseya/gocommon/pkg/restclient"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func CreateIRepo(client *mongo.Client, restClient restclient.RestClient) (IRepo, error) {
	iRepo := NewImpl(client)
	return iRepo, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
