// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/blackhorseya/gocommon/pkg/restclient"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func CreateIRepo(rw *sqlx.DB) (ITodoRepo, error) {
	iTodoRepo := NewMariadb(rw)
	return iTodoRepo, nil
}

func CreateHTTP(opts *Options, client restclient.RestClient) (ITodoRepo, error) {
	iTodoRepo := NewHTTP(opts, client)
	return iTodoRepo, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewMariadb)

var httpProviderSet = wire.NewSet(NewHTTP)
