// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/blackhorseya/todo-app/internal/app/todo"
	"github.com/blackhorseya/todo-app/internal/app/todo/api/restful"
	health2 "github.com/blackhorseya/todo-app/internal/app/todo/api/restful/health"
	todo3 "github.com/blackhorseya/todo-app/internal/app/todo/api/restful/todo"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/health"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/health/repo"
	todo2 "github.com/blackhorseya/todo-app/internal/app/todo/biz/todo"
	repo2 "github.com/blackhorseya/todo-app/internal/app/todo/biz/todo/repo"
	"github.com/blackhorseya/todo-app/internal/pkg/app"
	"github.com/blackhorseya/todo-app/internal/pkg/entity/config"
	"github.com/blackhorseya/todo-app/internal/pkg/infra/database"
	"github.com/blackhorseya/todo-app/internal/pkg/infra/generator"
	"github.com/blackhorseya/todo-app/internal/pkg/infra/log"
	"github.com/blackhorseya/todo-app/internal/pkg/infra/transports/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateApp serve caller to create an injector
func CreateApp(path2 string) (*app.Application, error) {
	viper, err := config.New(path2)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	todoOptions, err := todo.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	httpOptions, err := http.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	databaseOptions, err := database.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	client, err := database.NewMongo(databaseOptions)
	if err != nil {
		return nil, err
	}
	iRepo := repo.NewImpl(client)
	iBiz := health.NewImpl(logger, iRepo)
	iHandler := health2.NewImpl(iBiz)
	repoIRepo := repo2.NewImpl(logger, client)
	generatorOptions, err := generator.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	node, err := generator.New(generatorOptions)
	if err != nil {
		return nil, err
	}
	todoIBiz := todo2.NewImpl(logger, repoIRepo, node)
	todoIHandler := todo3.NewImpl(logger, todoIBiz)
	initHandlers := restful.CreateInitHandlerFn(iHandler, todoIHandler)
	engine := http.NewRouter(httpOptions, logger, initHandlers)
	server, err := http.New(httpOptions, logger, engine)
	if err != nil {
		return nil, err
	}
	application, err := todo.New(todoOptions, logger, server)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

var providerSet = wire.NewSet(log.ProviderSet, config.ProviderSet, generator.ProviderSet, http.ProviderSet, database.ProviderSet, todo.ProviderSet, restful.ProviderSet, biz.ProviderSet)
