// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package biz is a generated GoMock package.
package biz

import (
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkflowBiz is a mock of IWorkflowBiz interface.
type MockIWorkflowBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkflowBizMockRecorder
}

// MockIWorkflowBizMockRecorder is the mock recorder for MockIWorkflowBiz.
type MockIWorkflowBizMockRecorder struct {
	mock *MockIWorkflowBiz
}

// NewMockIWorkflowBiz creates a new mock instance.
func NewMockIWorkflowBiz(ctrl *gomock.Controller) *MockIWorkflowBiz {
	mock := &MockIWorkflowBiz{ctrl: ctrl}
	mock.recorder = &MockIWorkflowBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkflowBiz) EXPECT() *MockIWorkflowBizMockRecorder {
	return m.recorder
}
