// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package repository

import (
	"github.com/blackhorseya/todo-app/internal/pkg/config"
	"github.com/blackhorseya/todo-app/internal/pkg/databases"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateTaskRepo(cfg string) (TaskRepo, error) {
	configConfig, err := config.NewConfig(cfg)
	if err != nil {
		return nil, err
	}
	client, err := databases.NewMongo(configConfig)
	if err != nil {
		return nil, err
	}
	taskRepo := NewImpl(client)
	return taskRepo, nil
}

// wire.go:

var testProviderSet = wire.NewSet(databases.NewMongo, config.ProviderSet, NewImpl)
