// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/ekko/adapter/cli/app"
	"github.com/blackhorseya/ekko/pkg/adapters"
)

// Injectors from wire.go:

func NewCmd() (adapters.CLI, error) {
	cli := app.NewCmd()
	return cli, nil
}
