// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package todo

import (
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/todo/repo"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func CreateIBiz(logger *zap.Logger, repo2 repo.IRepo) (IBiz, error) {
	iBiz := NewImpl(logger, repo2)
	return iBiz, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
