// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package todo

import (
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/todo/repo"
	"github.com/blackhorseya/todo-app/internal/pkg/infra/node"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateIBiz serve user to create health biz
func CreateIBiz(repo2 repo.ITodoRepo, node2 node.Generator) (ITodoBiz, error) {
	iTodoBiz := NewImpl(repo2, node2)
	return iTodoBiz, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
