// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/blackhorseya/todo-app/internal/app"
	"github.com/blackhorseya/todo-app/internal/app/router"
)

// Injectors from wire.go:

func BuildInjector() (*app.Injector, func(), error) {
	routerRouter := &router.Router{}
	engine := app.NewGinEngine(routerRouter)
	injector := &app.Injector{
		Engine: engine,
	}
	return injector, func() {
	}, nil
}
