// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/blackhorseya/todo-app/internal/app"
	"github.com/blackhorseya/todo-app/internal/app/apis"
	"github.com/blackhorseya/todo-app/internal/app/biz/health"
	"github.com/blackhorseya/todo-app/internal/app/config"
	"github.com/blackhorseya/todo-app/internal/app/router"
)

// Injectors from wire.go:

func CreateApp(cfg string) (*app.Injector, func(), error) {
	biz := health.NewImpl()
	apisHealth := &apis.Health{
		HealthBiz: biz,
	}
	routerRouter := &router.Router{
		HealthAPI: apisHealth,
	}
	engine := app.NewGinEngine(routerRouter)
	configConfig, err := config.NewConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	injector := &app.Injector{
		Engine: engine,
		C:      configConfig,
	}
	return injector, func() {
	}, nil
}
