// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/blackhorseya/todo-app/internal/app"
	health2 "github.com/blackhorseya/todo-app/internal/app/apis/health"
	task2 "github.com/blackhorseya/todo-app/internal/app/apis/task"
	"github.com/blackhorseya/todo-app/internal/app/biz/health"
	"github.com/blackhorseya/todo-app/internal/app/biz/health/repository"
	"github.com/blackhorseya/todo-app/internal/app/biz/task"
	repository2 "github.com/blackhorseya/todo-app/internal/app/biz/task/repository"
	"github.com/blackhorseya/todo-app/internal/app/router"
	"github.com/blackhorseya/todo-app/internal/pkg/config"
	"github.com/blackhorseya/todo-app/internal/pkg/databases"
)

// Injectors from wire.go:

func CreateApp(cfg string) (*app.Injector, func(), error) {
	configConfig, err := config.NewConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	client, err := databases.NewMongo(configConfig)
	if err != nil {
		return nil, nil, err
	}
	healthRepo := repository.NewImpl(client)
	biz := health.NewImpl(healthRepo)
	iHandler := health2.NewImpl(biz)
	taskRepo := repository2.NewImpl(client)
	taskBiz := task.NewImpl(taskRepo)
	taskIHandler := task2.NewImpl(taskBiz)
	routerRouter := &router.Router{
		C:             configConfig,
		HealthHandler: iHandler,
		TaskHandler:   taskIHandler,
	}
	engine := app.NewGinEngine(routerRouter, configConfig)
	injector := app.NewInjector(engine, configConfig)
	return injector, func() {
	}, nil
}
