// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restful

import (
	"github.com/blackhorseya/ekko/internal/pkg/config"
	"github.com/blackhorseya/ekko/internal/pkg/httpx"
	"github.com/blackhorseya/ekko/pkg/adapters"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func NewService(config2 *config.Config, logger *zap.Logger) (adapters.Restful, error) {
	engine := httpx.NewRouter()
	server := httpx.NewServer(config2, logger, engine)
	restful := newRestful(logger, server, engine)
	return restful, nil
}

// wire.go:

var providerSet = wire.NewSet(httpx.ServerSet, newRestful)
