// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migration

import (
	"github.com/blackhorseya/ekko/internal/pkg/config"
	"github.com/blackhorseya/ekko/internal/pkg/storage/mariadb"
	"github.com/golang-migrate/migrate/v4"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func NewMigration(config2 *config.Config, logger *zap.Logger) (*migrate.Migrate, error) {
	db, err := mariadb.NewMariadb(config2, logger)
	if err != nil {
		return nil, err
	}
	migrateMigrate, err := mariadb.NewMigration(config2, db)
	if err != nil {
		return nil, err
	}
	return migrateMigrate, nil
}

// wire.go:

var providerSet = wire.NewSet(mariadb.NewMariadb, mariadb.NewMigration)
