apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
{{- include "helm.labels" . | nindent 4 }}
data:
  app.yaml: |-
{{- if .Values.app }}
{{ tpl .Values.app . | indent 4 }}
{{- end }}
