// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/ekko/internal/pkg/config"
)

// Injectors from wire.go:

func NewConfig(path string) (*config.Config, error) {
	configConfig, err := config.NewWithPath(path)
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}
