// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package health

import (
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/health/repo"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateIBiz serve user to create health biz
func CreateIBiz(repo2 repo.IRepo) (IBiz, error) {
	iBiz := NewImpl(repo2)
	return iBiz, nil
}

// wire.go:

var testProviderSet = wire.NewSet(
	NewImpl,
)
