// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package health

import (
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/health/repo"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateHealthBiz(repo repo.IRepo) (IBiz, error) {
	biz := NewImpl(repo)
	return biz, nil
}

// wire.go:

var testProviderSet = wire.NewSet(
	NewImpl,
)
