// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rest

import (
	"github.com/blackhorseya/ekko/adapter/platform/wirex"
	"github.com/blackhorseya/ekko/app/infra/configx"
	"github.com/blackhorseya/ekko/pkg/adapterx"
	"github.com/blackhorseya/ekko/pkg/logging"
	"github.com/blackhorseya/ekko/pkg/transports/httpx"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

import (
	_ "github.com/blackhorseya/ekko/adapter/api/platform_rest"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Servicer, error) {
	application, err := initApplication()
	if err != nil {
		return nil, err
	}
	injector := &wirex.Injector{
		A: application,
	}
	server, err := httpx.NewServer()
	if err != nil {
		return nil, err
	}
	servicer := newService(injector, server)
	return servicer, nil
}

// wire.go:

func initApplication() (*configx.Application, error) {
	app, err := configx.LoadApplication(&configx.C.PlatformRest)
	if err != nil {
		return nil, err
	}

	err = logging.InitWithConfig(app.Log)
	if err != nil {
		return nil, err
	}

	return app, nil
}

var providerSet = wire.NewSet(wire.Struct(new(wirex.Injector), "*"), initApplication, httpx.NewServer)
