app:
  name: todo
  nodeID: 1

http:
  host: ""
  port: 8080

log:
  level: "debug"

db:
  debug: true
  url: "mongodb+srv://root:%;4\X$fB*>`6kq:h@side.exsla.mongodb.net/todo?retryWrites=true&w=majority"
