# runMode can be [release, test, debug]
runMode: "debug"

http:
  host: ""
  port: 8080

log:
  format: ""
  level: "debug"

db:
  debug: true
  url: "mongodb://todo-app:changeme@localhost:27017/todo-db/?connect=direct&authSource=todo-db"

api:
  endpoint: "https://localhost:5000/api"
