# runMode can be [release, test, debug]
runMode: "debug"

http:
  host: ""
  port: 8080

swagger:
  enabled: true

log:
  format: ""
  level: "debug"

db:
  debug: true
  url: "mongodb://root:changeme@localhost:27017/?connect=direct&authSource=admin"
