app:
  endpoint: http://localhost:1992

http:
  host: 0.0.0.0
  port: 1992
  mode: debug

db:
  dsn: "root:changeme@tcp(localhost:3306)/ekko?charset=utf8mb4&parseTime=True&loc=Local"
  conns: 100
  source: "github://blackhorseya/ekko/scripts/migrations"

log:
  format: console
  level: debug

jwt:
  issuer: ekko
  signature: changeme

