platformRest:
  name: ekko-platform-rest

  log:
    level: debug
    format: console

  http:
    port: 8080
    mode: debug

  storage:
    mongodb:
      dsn: mongodb://root:changeme@mongodb/?retryWrites=true&w=majority
