// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	"github.com/blackhorseya/ekko/internal/app/domain/user/biz/repo"
	"github.com/blackhorseya/ekko/pkg/entity/domain/user/biz"
	"github.com/blackhorseya/ekko/pkg/genx"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateBiz(repo2 repo.IRepo, node genx.Generator) biz.IBiz {
	iBiz := NewImpl(repo2, node)
	return iBiz
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
