basePath: /api
definitions:
  entities.Task:
    properties:
      completed:
        type: boolean
      createAt:
        type: integer
      id:
        type: string
      title:
        type: string
    type: object
info:
  contact:
    email: blackhorseya@gmail.com
    name: Sean Cheng
    url: https://blog.seancheng.space
  description: Todo list API
  license:
    name: GPL-3.0
    url: https://spdx.org/licenses/GPL-3.0-only.html
  title: Todo list API
  version: 0.0.1
paths:
  /liveness:
    get:
      consumes:
      - application/json
      description: to know when to restart an application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Liveness
      tags:
      - Health
  /readiness:
    get:
      consumes:
      - application/json
      description: Show application was ready to start accepting traffic
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Readiness
      tags:
      - Health
  /v1/tasks:
    get:
      consumes:
      - application/json
      description: list all tasks
      parameters:
      - default: 1
        description: page
        in: query
        name: page
        type: integer
      - default: 3
        description: size of page
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Task'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List
      tags:
      - Task
    post:
      consumes:
      - application/json
      description: create a task
      parameters:
      - description: new task
        in: body
        name: newTask
        schema:
          $ref: '#/definitions/entities.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Task'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create
      tags:
      - Task
  /v1/tasks/{id}:
    delete:
      consumes:
      - application/json
      description: remove a task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Remove
      tags:
      - Task
    patch:
      consumes:
      - application/json
      description: modify information of task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: completed of task
        in: query
        name: completed
        type: string
      - description: title of task
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: ModifyInfo
      tags:
      - Task
swagger: "2.0"
