// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/ekko/internal/adapter/cli"
	"github.com/blackhorseya/ekko/internal/pkg/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeService serve caller to initialize service
func InitializeService() (*Service, error) {
	viper := config.NewConfig()
	adaptersCLI := cli.NewCLI(viper)
	service, err := NewService(adaptersCLI)
	if err != nil {
		return nil, err
	}
	return service, nil
}

// wire.go:

var providerSet = wire.NewSet(config.NewViperSet, cli.ProviderSet, NewService)
