// Code generated by MockGen. DO NOT EDIT.
// Source: dialer.go

// Package fuglex is a generated GoMock package.
package fuglex

import (
	reflect "reflect"

	contextx "github.com/blackhorseya/ekko/pkg/contextx"
	gomock "go.uber.org/mock/gomock"
)

// MockDialer is a mock of Dialer interface.
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
}

// MockDialerMockRecorder is the mock recorder for MockDialer.
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance.
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// IntradayQuote mocks base method.
func (m *MockDialer) IntradayQuote(ctx contextx.Contextx, symbol string) (*IntradayQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntradayQuote", ctx, symbol)
	ret0, _ := ret[0].(*IntradayQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntradayQuote indicates an expected call of IntradayQuote.
func (mr *MockDialerMockRecorder) IntradayQuote(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntradayQuote", reflect.TypeOf((*MockDialer)(nil).IntradayQuote), ctx, symbol)
}
