// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package todo

import (
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/todo"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

import (
	_ "github.com/blackhorseya/gocommon/pkg/er"
)

// Injectors from wire.go:

// CreateIHandler serve user to create health api handler
func CreateIHandler(e *gin.Engine, biz todo.ITodoBiz) (IHandler, error) {
	iHandler := NewImpl(e, biz)
	return iHandler, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
