name: Docker

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/docker.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
          restore-keys: |
              bazel

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          cache: true

      - name: Test
        run: |
          make test-go

      - name: Build
        run: |
          make build-go

      - name: Login to gcr
        uses: docker/login-action@v2.1.0
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Push image
        run: |
          make push-image

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          prerelease: false
          makeLatest: true