name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.go"
      - ".github/workflows/go.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.go"
      - ".github/workflows/go.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          cache: true

      - name: Test
        run: |
          make test-go
