name: Helm

on:
  push:
    branches:
      - main
    paths:
      - "deployments/charts/**"
      - ".github/workflows/helm.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "deployments/charts/**"
      - ".github/workflows/helm.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.0

      - name: Run Helm lint
        run: |
          make lint-helm

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.0

      - name: Authenticate with Google Cloud Platform
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          project_id: sean-side

      - name: Helm add plugin
        run: make install-helm-plugins

      - name: Helm repo add
        run: make add-helm-repo

      - name: Helm package
        run: make package-helm

      - name: Helm push
        run: make push-helm