name: Helm

on:
  push:
    branches:
      - main
    paths:
      - 'app/infra/charts/**'
  workflow_dispatch: { }

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        run: |
          echo "Installing chart-releaser"
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz -C "/usr/local/bin/"
          rm -f cr.tar.gz
          
          echo "Chart Releaser version"
          cr version
