// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/gocommon/pkg/restclient"
	"github.com/blackhorseya/todo-app/internal/app/todo/api/cmd"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/todo"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/todo/repo"
	"github.com/blackhorseya/todo-app/internal/pkg/infra/node"
	"github.com/google/wire"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func CreateApp() (*cobra.Command, error) {
	viper, err := cmd.NewViper()
	if err != nil {
		return nil, err
	}
	options, err := repo.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	restClient := restclient.NewClient()
	iTodoRepo := repo.NewHTTP(options, restClient)
	generator, err := node.NewImpl()
	if err != nil {
		return nil, err
	}
	iTodoBiz := todo.NewImpl(iTodoRepo, generator)
	command, err := cmd.NewRootCmd(iTodoBiz)
	if err != nil {
		return nil, err
	}
	return command, nil
}

// wire.go:

var providerSet = wire.NewSet(restclient.ProviderSet, node.ProviderSet, cmd.ProviderSet, biz.ProviderSetViaHTTP)
