// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/todo-app/internal/app/todo/api/cmd"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/todo"
	"github.com/blackhorseya/todo-app/internal/app/todo/biz/todo/repo"
	"github.com/google/wire"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func CreateApp() (*cobra.Command, error) {
	viper, err := cmd.NewViper()
	if err != nil {
		return nil, err
	}
	options, err := repo.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	iRepo := repo.NewHTTP(options)
	iBiz := todo.NewImpl(iRepo)
	command, err := cmd.NewRootCmd(iBiz)
	if err != nil {
		return nil, err
	}
	return command, nil
}

// wire.go:

var providerSet = wire.NewSet(cmd.ProviderSet, biz.ProviderSetViaHTTP)
